export type Participant = {
  id: string;
  registrationNumber: string;
  firstName: string;
  middleName: string | null;
  lastName: string;
  gender: string | null;
  dateOfBirth: string | null;
  email: string;
  phone: string | null;
  country: string;
  countryCode: string;
  passportNumber: string | null;
  rotaryId: string | null;
  city: string | null;
  organization: string | null;
  position: string | null;
  alternatePhone: string | null;
  facebookAccount: string | null;
  whatsapp: string | null;
  instagram: string | null;
  shirtSize: string | null;
  emergencyContactName: string | null;
  emergencyContactRelationship: string | null;
  emergencyContactPhone: string | null;
  emergencyContactEmail: string | null;
  dietaryRestrictions: string | null;
  medicalConditions: string | null;
  specialAssistance: string | null;
  paymentMethod: string | null;
  proofOfPaymentFileName: string | null;
  status: "PENDING" | "CONFIRMED" | "CANCELLED" | "REJECTED";
  adminNotes: string | null;
  registrationDate: string;
  createdAt: string;
  updatedAt: string;
};
